# -*- coding: utf-8 -*-
#Entities_list = [
#    'pai',
#    'doc_origem',
#    'data_nascimento',
#    'nome',
#    'unknown',
#    'data_expedicao',
#    'naturalidade',
#    'cpf',
#    'rg',
#    'mae'
#]

Entities_list = [
    "eh-idoso",
    "info-rg",
    "info-nome",
    "rg",
    "meta",
    "estado-emissao",
    "info-naturalidade",
    "info-dataexp",
    "info-datanasc",
    "data-nascimento",
    "data-expedicao",
    "info-filiacao",
    "org",
    "filiacao",
    "nome",
    "info-cpf",
    "cpf",
    "naturalidade",
    "info-asstitular",
    "ass-titular",
    "info-assdiretor",
    "ass-diretor",
    "info-coordenador",
    "coordenador",
    "via",
    "info-docorigem",
    "doc-origem",
    "info-perm",
    "info-acc",
    "info-local",
    "local",
    "info-dataemissao",
    "data-emissao",
    "info-obs",
    "obs",
    "info-primeirahab",
    "primeira-hab",
    "info-validade",
    "validade",
    "info-cathab",
    "cat-hab",
    "info-renach",
    "renach",
    "uf",
    "info-doc",
    "doc-id",
    "org-emissor",
    "unknown",
    "comarca",
    "certidao-origem",
    "polegar"
]

